export * from "./genresListPage/GenresListPage"
export * from "./genreCardPage/GenreCardPage"
export * from "./genreInfoPage/GenreInfoPage"
export * from "./movieCardPage/MovieCardPage"
export * from "./moviesListPage/MoviesListPage"
export * from "./notfoundPage/NotFoundPage"
export * from "./movieInfoPage/MovieInfoPage"
